### PR TITLE
holiday theme with new holiday frame overlay + snow on home effect

### PR DESCRIPTION
**Pull request by mgonzales71**
Created a new festive colored holiday theme for titan (used master/jarvis branch) but you can apply to isengard as well if you like.

screenshot of theme

happy holidays

also included a new overlay that is used with theme

holiday frame

Hope you like!

Mario

### CODE REVIEW

**Comment by mgonzales71** [comment]
Got bored and added a little more to this PR - hehe 

another addition for your review - hope you like
:snowflake: :snowman: :snowflake: :snowman: :snowflake: :snowman: :snowflake: :snowman: 

:grinning: 

snow on home effect / skin setting option

**Comment by mgonzales71** [comment]
option to expand snow effect to other parts of the skin
visible / effective only if: !headers only on home + !show only weather instead of title

**Comment by marcelveldt** [comment]
Hi Mario, great work. This was actually requested by users on the forums :-)

One thing however.. Do you think it's possible to create this PR against the isengard branch ?
That way I can merge the changes up into the master branch but I cannot merge it down into the isengard branch

**Comment by mgonzales71** [comment]
Ok let me re-do it against Isengard - shouldn't take long.

Sounds like PR's should all go to Isengard for now.  Sorry I should have asked ;)

Q - will you be switching that to Jarvis anytime soon?  (Just want to know if and when I should change)

**Comment by mgonzales71** [comment]
ok - new PR against Isengard done - https://github.com/marcelveldt/skin.titan/pull/161

glad you like.  please test, I made changes against local checked out copy - haven't yet tested them but going to do that now.  I am pretty sure they changes are good to go but always better with more then one tester :smile:  let it snow hehe :snowflake:

**Pull request closed without merging**
