### PR TITLE
OSDProgressBarCacheColor skin option

### PR DESCRIPTION
**Pull request by mgonzales71**
OSDProgressBarCacheColor skin option
seek nib control is also now visible

tried to define white as default for Cache Color in IncludesSkinSettings
but does no seem to load (saw an undefined error in log file until I
defined it via color picker in the skin) - the cache is by default white
anyway (texture used is white so if not defined works as white anyway)

the cache color will always be tinted by the BG color - could not find good way to work around this with better results.

example photos ....

### CODE REVIEW

**Comment by mgonzales71** [comment]
suggest the option of a thin box around progress bar in slimOSD mode so progress background color can be set to none and look nice like it does in OSDModern with same settings.

**Comment by marcelveldt** [comment]
If the user wants to disable it, there should also be a visibility condition on the control. If the skinsetting is set to none, it should hide the whole control.

**Comment by marcelveldt** [comment]
the default should be set in IncludesDefaultSkinSettings.xml

**Comment by marcelveldt** [comment]
I will merge the PR and fix these two suggestions. myself. Thanks for this!

**Comment by marcelveldt** [comment]
Oops, I missed the fact that you had already added the default to incudesdefaultskinsettings ;-)

**Comment by mgonzales71** [comment]
yea - I had added the defaults to the file... just didn't load.

also - i am seeing:

23:09:35 T:9876 WARNING: Skin has invalid include: FontColorWhite

I see where the include is called to load but haven't found out where it's defined (yet)

and you are right - i should  have included a visible statement as well - thanks for adding it for me.

**Pull request merged**
