### PR TITLE
skin support/customization of screensaver.digitalclock

### PR DESCRIPTION
**Pull request by mgonzales71**
supports version 2.8.0 and up screensaver.digitalclock
git - https://github.com/vdb86/screensaver.digitalclock
(edited)

### CODE REVIEW

**Comment by mgonzales71** [comment]
hey Marcel - hold off on this PR... I am working on a retro-flip-clock mod for it via skin xml customization.

I think I will add a skin setting "enable retro flip clock skin mod for screensaver.digitalclock" so I can support the screensaver with it's default settings/controls but also allow the user to apply a mod via the skin if they wish.

here is what I have so far -- it's almost done - just want to test and tweak some more

also showed this to the screensavers author - waiting for his feedback as well.  he has added alot off my feedback so he could end up adding this too.

this is my fav kodi screensaver by far - very lightweight and has become skin friendly too,

photos are of 24 hour and 12 hour time support as set by appearance - international setting in the skin

**Comment by mgonzales71** [comment]
ok all done - PR is now ready.

try it out - let me know what you think.

skin setting for screensaver.digitalclock custom skin display

if enabled:

retro style flip clock display - will honor 12 / 24 hour clock based on international settings in appearance

fixed info display of now playing, date, current weather cond and icon (based on set selected in skin)

still honors background image / color display from screensaver settings

new setting in skin:



display if NOT enabled - will honor all screensaver settings:



display if ENABLED
will only honor screensaver settings for background image/color settings
all other info is skin customized

**Comment by mgonzales71** [comment]
couldn't resist adding more fit and polish :smile:

decided to include theme color settings, clock background panel, etc




screensaver with skin customization in action
(music playing to demonstrate now playing info line)

https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!5957&parId=599DA6BD82779E65!4605&authkey=!ANtncXuFcVnqRw4&ithint=video%2cmp4

screensaver in typical state - nothing playing

https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!5958&parId=599DA6BD82779E65!4605&authkey=!ACu99WbcTHnY-2Q&ithint=video%2cmp4

OK.... now I think I am done!  hehe - well unless you want me to change, adjust anything :laughing:

**Comment by marcelveldt** [comment]
Nice work Mario!

Just one thing: please add a visibility condition for the button in skinsettings to only show the button when the script is installed instead of the current install if not present condition. Kodi has it's own dialog for selecting the screensaver, we should respect that. For any other optional addons I use indeed that install to enable approach but just not with these kind of addons because they need to be selected in the kodi settings...

**Comment by mgonzales71** [comment]
Ok - so no install the addon if it is not installed already and make it invisible if not already installed

I understand where you're coming from I just thought it be nice to have a quick easy way to install it for the user if they didn't already have it.

Maybe I should just fork the code and write a new "Titan" retro digital flip clock screen saver :)

Then maybe you the helper script could be used to make the setting change for the user? Lol

I am in a silly mood today! Oh Marcel - I think it is too much Halloween candy my sister has around. 

Hey question for you:

it is there an easy way to display a dialog with text and the OK button from the skin it self?  (DialogOk) or do you have to run a script to do it?  and I'm not talking about the  Toast notification built in function.

I couldn't find one except a python script or addon.

What I am trying to do it post a dialog with a header, scrollable textbox and then an ok button.

Maybe that's a feature you can add to your helper script if you think others would also find that useful.

Thanks again marcel!

Mario

**Comment by marcelveldt** [comment]
The installing is fine, I did that trick with all other scripts. It's just the fact that installing isn't enough, it also needs to be set as the default screensaver and that's where Kodi has a nice dialog for...
So, the auto install trick with the onclick condition is fine as long there are no other requirements to get that addon to work.

I can add a dialogOK messagebox in the skinhelper, is that OK ?

**Comment by mgonzales71** [comment]
oh that would be awesome.
I think adding skinnable access to DialogOK and even maybe DialogYesNo would be great additions.

btw the reason for the access to the dialog to present text was to give feedback to the user that:
1) they would need to enable to screensaver after it was installed
2) what the skin specific customizations are.

my other thought was to fork the digital clock screensaver, simplify the code/options and make my changes that way.

**Comment by mgonzales71** [comment]
the other option was to take the https://github.com/robwebset/screensaver.weather route which basically just does:

 # Load the screensaver window
        xbmc.executebuiltin("ActivateWindow(Weather)", True)

with your helper script to display image slideshows of various types all the code is almost already in the custom xml file I already have ready to go.

maybe that is a better way to go?

hmmm

OH - before I forget - I noticed the orange/pumpkin theme was gone - was there a problem and I missed a message or something?  sorry if I did miss a message - been sick the last week.

feeling much better now

**Comment by marcelveldt** [comment]
Mario, the OK dialog support has been added to skinhelper:  https://github.com/marcelveldt/script.skin.helper.service/commit/995f6fcecca48deac2a3bae60ae51d9a26c8a27a

Please let me know once you're ready so this can get merged.

**Comment by mgonzales71** [comment]
need to rework once jarvis screensaver bug is fixed... 
http://trac.kodi.tv/ticket/16361
closing for now.  will re-open.

**Pull request closed without merging**
