### PR TITLE
New for Krypton - DialogPlayerProcessInfo.xml

### PR DESCRIPTION
**Pull request by mgonzales71**
Fully localized using latest krypton nightly and titan krypton beta branch

screenshots showing PR dialog(s)

### CODE REVIEW

**Comment by mgonzales71** [comment]
oops!

I just noticed you added a bunch of strings to another branch - that will impact this PR assuming those strings will carry forward to krypton branch.   

let me know how you want to handle this.

Could renumber them (with a kryton+ numeric prefix) or would you just rather they be added to isengard/master as well even if the changes are for krypton?

**Comment by marcelveldt** [comment]
I did not yet merge the changes in master to the krypton branch, sorry!
I will do that right now so you can proceed with the merge of this PR.

Sorry again

**Comment by marcelveldt** [comment]
merge is completed, krypton branch now has the latest changes I did apply to master (jarvis)

**Comment by mgonzales71** [comment]
OK -I resolved the conflicts and we should be good to go :smiley:

**Comment by mgonzales71** [comment]
also updated settings.xml for krypton (librarysettings) now (mediasettings)
does anything need to be updated in the skin/shortcuts/helper for this change?

**Comment by mgonzales71** [comment]
Think I found part of my answer regarding mediasettings rename:

10:26:14 T:6108   ERROR: Window Translator: Can't find window librarysettings

also appears to be related for krypton:

10:25:54 T:6108   ERROR: Window Translator: Can't find window mutebug
10:25:54 T:6108   ERROR: Window Translator: Can't find window infodialog
10:26:09 T:6108   ERROR: Window Translator: Can't find window videolibrary
10:26:09 T:6108   ERROR: Window Translator: Can't find window musiclibrary

**Comment by marcelveldt** [comment]
thanks Mario!

I already did a bunch of fixes for Krypton, bu I'm behind a few weeks with changes.
I'll take a look which ones I've missed later this week

**Pull request merged**
