### PR TITLE
fix to make ProgressbarCache visible in OSD

### PR DESCRIPTION
**Pull request by mgonzales71**
fix to make ProgressbarCache visible in OSD

### CODE REVIEW

**Comment by mgonzales71** [comment]
also added the following proposed change as well:

https://github.com/mgonzales71/skin.titan/commit/d3c2e4cc8855cb66dade84989b76e2624e5fd845

progress slider nib visibility for slim and modern OSD
see example screenshots - prior to this proposed change - the nib was
transparent and solid color matching the progress bar itself making is
almost impossible to see.

**Comment by mgonzales71** [comment]
SlimOSD should have cache progress visible as well :)

**Comment by marcelveldt** [comment]
thanks Mario!
One question... Does this also cover the scenario where the OSD progress bar background color is set to None (which is the default) ?

**Comment by mgonzales71** [comment]
Ok - I am going to re-work this pull request.  closing this one and will re-open a new one that deals with none being the default bg color for progressbar

**Pull request closed without merging**
