### PR TITLE
option to display WeatherInfoOSD with slim OSD

### PR DESCRIPTION
**Pull request by mgonzales71**
option to display WeatherInfoOSD with slim OSD

### CODE REVIEW

**Comment by marcelveldt** [comment]
Hi Mario, looking good.
Just one comment: What happens if a user has not enabled that infopanel on top ?
In that case it should have a slide animation so the weather would be positioned more to the top

**Comment by mgonzales71** [comment]
this should help...

added change to the PR:

**Comment by mgonzales71** [comment]
also just added another another commit with a conditional to display weather at top when Skin.HasSetting(EnableOSDInfo) + !Window.IsActive(DialogFullScreenInfo.xml)

think that covers all the possible situations where it would end up lower when top info panel is not displayed

**Comment by marcelveldt** [comment]
merged, thanks!

**Pull request merged**
