### PR TITLE
add missing icons for krypton

### PR DESCRIPTION
**Pull request by mgonzales71**
add missing icons for krypton

### CODE REVIEW

**Comment by mgonzales71** [comment]
screenshot of icons in use (don't have any add ons that need updating to see the 6th icon) but you can view it in the PR :smile: 

screenshot013

**Comment by mgonzales71** [comment]
screenshot014
screenshot015

**Comment by mgonzales71** [comment]
updated/redesigned defaultaddonsrecentlyupdated icon

defaultaddonsrecentlyupdated

**Comment by marcelveldt** [comment]
great work again !

**Pull request merged**
