### PR TITLE
added missing numeric jump/seek to specific time (changed in krypton) + weatheralert+bufferprogress options

### PR DESCRIPTION
**Pull request by mgonzales71**
added missing numeric jump/seek to specific time (changed in krypton)

**also**

- added optional display of buffering progress

- added optional display of a weather alert indicator overlay for weather icons in skin during active weather alert if supported by weather addon

**Settings:**

**Jump / Seek to Specific Time of Video**

**Buffering Progress Indicator Option**

**Couple of examples of Weather Alert Indicator Icon Overlay Option**

### CODE REVIEW

**Comment by mgonzales71** [comment]
updated PR.
give me a few mins to re-test.  will update PR comments once I have.

**Comment by mgonzales71** [comment]
looks good.  updated direct seek/jump and buffer progress to use OSDpanel color and OSD text color and shadow color

examples:
screenshot027
screenshot005

**Comment by mgonzales71** [comment]
this corrects the issue that I overlooked that the id's were uniquely significant for this window
- just fixed and recreated the jarvis version of the PR as well.

sorry 😏

**Comment by marcelveldt** [comment]
merge magic done :-)

**Pull request merged**
