### PR TITLE
re-work of next up notification dialogs

### PR DESCRIPTION
**Pull request by mgonzales71**
re-work of dialogs..  I know it's not smaller but it is in the same screen space as the InfoPanel uses - figured that would be better for consistency?  Thoughts?

### CODE REVIEW

**Comment by marcelveldt** [comment]
I think its much better! Maybe the only thing is that the buttons feel a bit misplaced? Perhaps align them left besides the poster?

**Comment by mgonzales71** [comment]
you are talking about the buttons in the 2nd picture correct?

**Comment by mgonzales71** [comment]
cosmetic updates pushed to PR/branch...

**Comment by mgonzales71** [comment]
final tweak :smile:  moved season/episode # to Episode title line..

**Comment by marcelveldt** [comment]
thanks Mario!

**Pull request merged**
