### PR TITLE
weather alert icon overlay and buffer progress OSD options for Jarvis

### PR DESCRIPTION
**Pull request by mgonzales71**
new/updated PR for Jarvis.

### CODE REVIEW

**Comment by mgonzales71** [comment]
FYI - just tested on my jarvis install - looks good.

**Comment by mgonzales71** [comment]
oh i am not sure but I think weather underground is the only weather addon that supports weather alerts.

not sure why no one has written a weather addon to use https://www.ncdc.noaa.gov/cdo-web/webservices/v2 that also has weather alerts and I am pretty sure Met Office for the UK also supports them via the web not sure about the addon.

**Comment by marcelveldt** [comment]
Great stuff Mario!

**Comment by mgonzales71** [comment]
missed one commit for last PR before you merged this one so the new one that is open is not a dupe but fixes the oversight.

sorry i should have caught the fact that certain textures did not display because of the significance of id #'s for this windows

**Comment by RXIII-cyber-wizard** [comment]
Hey @marcelveldt i am trying to build a skin based on your titan skin,
All is going great, accept for the kodi logo in the left upper corner,
Could you please tell me how to clear that?

With kind regarts

**Comment by mgonzales71** [comment]
@RXIII-cyber-wizard 

find the texture controls(s) that use the texture(s) in question and go from there.

hint:  look in skin.titan\media\home\ for the logo(s) and then search the xml skin files for those textures.

**Comment by mgonzales71** [comment]
@RXIII-cyber-wizard also please make sure to properly credit code you use, make it available to the community at large and of course adhere to the license model that @marcelveldt has published under: https://github.com/marcelveldt/skin.titan/blob/master/LICENSE.txt  - thanks

**Pull request merged**
