### PR TITLE
update sliderex and slider controls

### PR DESCRIPTION
**Pull request by mgonzales71**
updated slider and sliderex controls
in addition uses activespincontrol color for nib color when control is focused

screenshots:

### CODE REVIEW

**Comment by mgonzales71** [comment]
Final thought:
Have not tested as fully on Jarvis branch as I have Krypton.

So... maybe should only merge with krypton branch?

**Comment by mgonzales71** [comment]
well I had time today to get an install of Jarvis setup so I can do testing with that branch of the skin and things seem to be fine with the changes,

a few screenshots of jarvis with changes in this PR:

preview

**Comment by marcelveldt** [comment]
Great stuff Mario!

FYI: I will add you as an author for the skin as you do so many work for the skin.
If you want I can also give you write permissions on the git repo ?

I will merge these changes in the master branch (jarvis) and then I will merge them into the krypton branch.

Again, thank you!

**Comment by mgonzales71** [comment]
That is very kind of you to do Marcel you didn't need to do that but thank you for that.

I don't need write access - lets hold off on that unless you forsee you needed to be away for an extended time and need to have someone who does require it to help in your absence,  Honestly I just get nervous as silly as it sounds that I would make some mistake LOL - I am fine with doing the PR, etc - it is how Git is suppose to work anyway and for now lets have you be the driver :smile:

As always I am very happy to help you out when and where I can.

I am really glad you and the family had an enjoyable summer and nice to see you are back.

Cheers! 

Mario

**Pull request merged**
