### PR TITLE
holiday theme, bg overlay for use with new theme and a falling snow e…

### PR DESCRIPTION
**Pull request by mgonzales71**
holiday theme, bg overlay for use with new theme and a falling snow effect skin option for display on home (plus option for other skin areas).

### CODE REVIEW

**Comment by mgonzales71** [comment]
just tested it with a test merge into a local copy of jarvis and all seems good.

one thing: I had added : ["bool", "enablesnow", "true"] to the holiday theme as a test and forgot to take it out - should I leave it or remove it from the PR?  It only enables snow effect on Home.

**Comment by mgonzales71** [comment]
in case you want to save time re-doing it here is a zip of the current master with a merge of this PR for testing 

https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!6074&parId=599DA6BD82779E65!4605&authkey=!AErQv22Lxz2pkus&ithint=file%2czip

**Comment by mgonzales71** [comment]
OK Marcel - made final commit for this PR (i hope) - reduced size of overlay

enjoy!

**Comment by mgonzales71** [comment]
i know I know - I couldn't resist... :christmas_tree: :smiley: 

added candy cane spinner

**Comment by marcelveldt** [comment]
haha Mario, you're on a roll :-)
Great work, I'm now goling to merge this in for a testdrive by users. Thanks!

BTW: If you have time some day, could you take a look at the english language file if all text is well formed US english ? I had a suggestion on the forums from someone saying that some text could be better formatted. E.g. start all sentences with a capital only instead of seperate words:

http://forum.kodi.tv/showthread.php?tid=247525&pid=2174158#pid2174158

While English is not my native language I thought you may want to have a quick peek for bad language :-)

**Comment by mgonzales71** [comment]
Will do :)

I'll look at it later tonight for ya.

And just so you know you do a great impression of an English speaker hehe

**Pull request merged**
