### PR TITLE
two new themes, new weather icon set and a few tweaks/fixes

### PR DESCRIPTION
**Pull request by mgonzales71**
Midnight and Snow Themes (Dark and the other Light):

midnight
snow

New Weather Icon Set and slight change to slider - before change white button would make it invisible.

other changes - a new fullscreencolor fade that looks at a few settings to choose a fade color

progress and progress_extended now follow busy indicator color since a black setting would make the progress not visible and no way to change it.

found an error with button includes - had a hard coded color of white - now properly follows theme color setting

hope you like.  let me know if I need to change anything, revert, etc

Thanks

Mario

### CODE REVIEW

**Comment by marcelveldt** [comment]
Mario, Not sure if I can accept this one...

That fullscreencolor_fade is a duplicate of dialogoverlay_extra.
In situations this is needed, the dialogoverlay_extra should be used for a consistent experience. I adjusted that to use the background colors.
If you want to change the fade color there's already a setting in skin settings --> background settings. Just set it with a color and you can also set the opacity. The dialogoverlay extra will always use the base color of the one you used in the background fade color.

Also, that hardcoded colro in the "Key" include was there on purpose because that's the include for the on screen keyboard. I don't think that should follow the default buttons colors at all. Those key buttons need to clearly visible from a distance and with some color themes that won't be possible, mainly because that key buttons use another texture which is already greyed.

Please look at background settings --> background color diffuse and let me know.

BTW: great work on the new color themes! I had to delete your old themes because too many changes were made in recent skin versions. I was hoping for you to send updates ones ;-)

**Comment by mgonzales71** [comment]
well - I can revert the changed for the color fade - I agree it should be consistent although I don;t think you overlay extra fade is transparent enough (too opaque - maybe that could be changed?)

If its a special case should the keyboard have it's own include?  

several of the dialog*.xml use the "key" include for the buttons and if you use a theme like the ones I just made you can end up with "blank" buttons ----> white text and a white button.

I will revert the fades now - let me know what you would like to do about the buttons and the condition I ran into.

thanks!

mario

**Comment by mgonzales71** [comment]
ok - backed out changes to and now using DialogOverlayExtra

let me know your thoughts on the keyboard and numeric keypad - I understand your thinking on this but if someone wants to intentionally sets the color of buttons to match the button color basically making them unreadable - or some hard to read from a distance color combo them let them :smile: but hard coding it causes issues they user can't resolve - don't you agree?  I say if they want to theme something horrible let them LOL

**Comment by mgonzales71** [comment]
btw - the keyboards look fine with the changes made 

also just noticed that the custom search brings up a second keyboard - is that supposed to happen?

**Comment by marcelveldt** [comment]
I totally agree woth you Mario that it should be customizable... It's just that I remember it causing issues and render the keyboard unreadable at some point but that might been pre-Isengard. In Isengard 15.1 the fixes were added for the colors. So, go ahead and add this in in the PR. I'll do some test if this is still ok. Could you please test if it still looks okay with the default blue theme please ?

Oh and yes the search opens a second keyboard dialog as soon as you press the top button (containing the search phrase). There's some issue when you have a edit control in there it would cause Kodi to crash at Close on Linux systems so I used a button instead.

**Comment by mgonzales71** [comment]
keyboards and dialogs seem to look ok with the default theme - the only item is the keys that have a graphic instead of a font character and then they display ok - just with a different color.








you mentioned before about being able to see the keyboard from a distance - I just noticed they characters in each "key" could be larger - that would also help in reading from a distance - seems like a lot of space per key could be used for larger font sizes maybe?

I think with themes like I just did where you have primarily just 2 colors white/black  or black/white (or blue/white, etc) we may still find issues - but I think what really highlighted them with these twho themes was the fact that text, shadow, etc are usually either white or black and some places are still hard coded - so try to run each theme for a day or two yourself and see if you can find anything that I missed.

So unless I missed something I think with these test we are ok to go ahead with the PR ? 

Thanks Marcel!

Mario

**Comment by mgonzales71** [comment]
oh side Q...



in weather's hourly forecast - is there an easy way to get to highlighted item to put the text on top instead of behind?

**Comment by mgonzales71** [comment]
oh and if I had a wish list for theme option additions:

home tiles:  label text color and label panel color :wink:

**Comment by marcelveldt** [comment]
OK, agreed with the color change. Keyboard doesn't look very nice now in default theme but that might just be the colors used in that theme. Something to change on a rainy day ;-)

Those images (arrows) should also be colored, I'll look into those

**Comment by mgonzales71** [comment]
I think you are thinking the "mainblue" for button focus color looks weird in the keyboard screen shots?

we could change the button focus color in the default theme to white and it would like like it used to in the keyboards :) hehehe 

regarding the images for special keys - I don't think you can get the font based arrows characters in Kodi - can you?  In windows they are called "alt codes" like alt+0149 was the bullet *(dot) if I recall.

but don't hesitate to ask if you need me to change, fix, etc anything else especially if you see anything with the new themes

Mario

**Comment by marcelveldt** [comment]
colors in weather is now fixed.

**Comment by mgonzales71** [comment]
I am now testing this PR + your latest commits with midnight theme and noticed one issue - as I suspected with one of the "special" keyboard keys only... 



are those keys hard coded to white or black?  I haven't looked at the code yet - so not sure if it is or not but as I suspected this problem most likely only happens when a theme has a lot of back or white in it.

**Comment by marcelveldt** [comment]
merged the PR... I will sort out that Arrow keys later today.

**Comment by marcelveldt** [comment]
already fixed...

**Comment by mgonzales71** [comment]
that was quick!  man are always fast as lightning Marcel hehe
I caught and fixed a few little things - looks like I got them in the PR just in time too!
:tada:

**Comment by marcelveldt** [comment]
Great stuff Mario, thanks for helping out!
I just adjusted the button color in default theme and cleaned up a few things.

Now it's testing time ;-)

Did you had time to test that forced views problem ?

**Comment by mgonzales71** [comment]
Yea I actually just finished testing again after I updated to 15.2 rc2 - i still see a delay but its seems to happen only once and is more noticeable the first entry in nodes/lists with a larger number of items.

i haven't had a crash since the app update and latest updates of the helpers and skin from git.

I will keep testing now that there is a lull in updates :)

glad to help as always!

Mario

**Pull request merged**
